name: super-functor-factory
version: 2022.0.0.0
github: "fpclass/super-functor-factory"
license: OtherLicense
author: "Michael B. Gale"
maintainer: "michael@fpclass.online"
copyright: "Copyright 2022 Michael B. Gale"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/fpclass/super-functor-factory#readme>

dependencies:
  - base >= 4.7 && < 5
  - random
  - hashable
  - ansi-terminal

library:
  source-dirs: src

executables:
  super-functor-factory:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - super-functor-factory
      - optparse-applicative

tests:
  super-functor-factory-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - super-functor-factory
      - tasty
      - tasty-hedgehog
      - tasty-hunit
      - tasty-ant-xml
      - hedgehog
